services:

  backend:
    container_name: MediaVault-backend
    build: ./backend/MediaVault-backend
    ports:
      - 8080:8080

  frontend:
    container_name: MediaVault-dev-frontend
    image: nginx:alpine 
    ports:
      - 3000:80
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend
